### PR TITLE
Use a static site generator

### PR DESCRIPTION
**Pull request by justusdieckmann**
With this, we can extract out the outer layout to one place.
We can use cache-busting versioning for css and js files, to enable much stronger caching on clients.
And we can insert the featured action without needing custom replacement scripts.

In cloudflare, it suffices to set the build command to `npm run build` and the build output directory to `_site`, (that should happen before merging this pr, so that merging this pr will trigger the first build which will then be deployed).

You can start a small development server that auto-refreshes when a file is updated with `npm run serve`.

The pull request looks like much, but that's mainly because pretty much all files were moved, and the header and footer refactored out of all files. There were no actual content changes, the new generated website looks exactly the same as the public one does now (with the only exception of a few pixels more space in the footer, because I put the credits in its own paragraph). 

You can see it live (build and hosted with cloudflare) here: https://d-tbfightersdotorg.pages.dev/.

I also like this change since it organizes the repo quite a bit

### CODE REVIEW

**Comment by YummyOreo** [comment]
I dont know if this is needed and some metadata doesnt have nofollow and noindex when it should

**Comment by justusdieckmann** [comment]
Can you say where the nofollow and noindex should be?

**Review by Nolram12345 — CHANGES_REQUESTED** [review]
See my comments on discord - TLDR:
I don't think the benefit of this is greater than the impedance to development and complexity for new contributors. We are already lacking in reviewers and contributors, so having something as complex as this is quite a big obstacle, and I don't see the benefit it brings us.

**Comment by Nolram12345** [comment]
Closing this for now. We may reopen this at a future point in time.

**Pull request closed without merging**
